# Configuration for request-info - https://github.com/behaviorbot/request-info

# *OPTIONAL* Comment to reply with
requestInfoReplyComment:
  - Ah no! young blade! That was a trifle short! Tell me more ! I am sure you can be more effusive. In short, we would appreciate it, if you could provide us with more info on this issue/pr! :D

requestInfoLabelToAdd: needs-more-info

# Keys must be lowercase. Valid values are 'issue' and 'pullRequest'
requestInfoOn:
  pullRequest: true
  issue: true
