name: NPM Version Bump

on:
  push:
    branches-ignore:
      - master
      - beta
      - develop

jobs:
  bump-version:
    name: Bump Package version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      
      - name: cat package.json
        run: cat package.json
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "cat package.json"
        run: cat ./package.json