name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not been looked at for the past month, marking it as stale. Remove stale label or comment or this will be closed in 5 days'
        stale-pr-message: 'Ooph! I have to mark this as a stale PR. It has not been looked at for a month. Remove stale label or comment or this will be closed in 5 days'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        exempt-issue-label: 'awaiting-approval'
        exempt-pr-label: 'awaiting-approval'
        days-before-stale: 30
        days-before-close: 5
